version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      DB_HOST: monorail.proxy.rlwy.net
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-iCpQvgIFIWszefTiXZrRIGpOPLUMXXGa}
      DB_NAME: ${DB_NAME:-railway}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: rafape2024/apirestfinance:latest
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: monorail.proxy.rlwy.net
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-iCpQvgIFIWszefTiXZrRIGpOPLUMXXGa}
      DB_NAME: ${DB_NAME:-railway}

volumes:
  postgres_data:
